### ISSUE TITLE
Formula not installing completions

### ISSUE THREAD

**Issue by CVirus** [localstack/homebrew-tap#4]
Good day,

From what I've seen in the past, a lot of brew formulas automatically generate and install their shell completions using `generate_completions_from_executable`.

[Here](https://github.com/Homebrew/homebrew-core/blob/da5c1d8ee4a3942f3b0cb5b657ded2f9f9f8835e/Formula/t/tt.rb#L38) is an example:
`generate_completions_from_executable(bin/"tt", "completion", shells: [:bash, :zsh])
`

Otherwise, you have to manually install and maintain the completions via `localstack completion zsh > "$(brew --prefix)/share/zsh/site-functions/_localstack"` for example for zsh.

**Comment by alexrashed** [comment]
That's a really interesting suggestion! Would be cool to have the autocompletion being configured automatically when the package is installed. However, this repo really only contains commit which are auto-generated from [localstack/localstack-cli](https://github.com/localstack/localstack-cli). This repo is responsible of building the binary packages of the CLI and - on releases - pushing a commit here referencing the new release artifacts.
So we would really have to update the GitHub action creating the commit here:
https://github.com/localstack/localstack-cli/blob/89b2e5d2dbec9b3563f4d15773cb8bc5e8b155ff/.github/workflows/homebrew.yml#L42-L47

Would you be interested in contributing a PR for this change? Otherwise I might pick this one up in the upcoming weeks (since this doesn't seem to be a pressing issue).

**Comment by CVirus** [comment]
Sure, let me see if I can squeeze in a couple of hours this weekend. I have zero experience with homebrew packaging and I never used localstack (apart from installing the CLI), but let's see :D

**Comment by alexrashed** [comment]
Thanks a lot for your contribution! The next time the action runs (we are about to release a patch release in the upcoming days) will contain the new completion config! 💯
